version: "2"
networks:
  letsencrypt:
services:
  server:
    restart: "always"
    build: .
    container_name: "server"
    environment:
      PORT: 3000
      VIRTUAL_HOST: camundacon-live.joshwulf.com
      LETSENCRYPT_HOST: camundacon-live.joshwulf.com
      LETSENCRYPT_EMAIL: josh.wulf@camunda.com
    networks:
      - letsencrypt
