version: "2"
networks:
  letsencrypt:
services:
  server:
    restart: "always"
    build: .
    container_name: "server"
    environment:
      PORT: 3000
      VIRTUAL_HOST: 18.156.32.160
      LETSENCRYPT_HOST: 18.156.32.160
      LETSENCRYPT_EMAIL: josh.wulf@camunda.com
    networks:
      - letsencrypt
